### ISSUE TITLE
Sculk Expansion | Datapack Addition

### ISSUE THREAD

**Issue by FumoSnake** [JPAchilles/20stm#1]
Edit: I thought I could add the enhancement label.

https://modrinth.com/datapack/sculk-expansion

This project can be incorporated through the datapack or mod folder. The key feature I read is that it allows the Warden to spread sculk as it walks. It is even capable of spawning sculk sensors and shriekers. I would find this addition being fantastic with the Sculk Horde mod especially how that mod changes how the overworld biomes converting into the Deep Dark. This datapack will allow the warden to spread the sculk horde, at least I believe the datapack will play nice with the mod.

Note, I have not playtested this, but if it works how I think it does, it will make the sculk horde even more terrifying than it already is.

**Comment by JPAchilles** [comment]
Will test this the soonest I get the opportunity to in a few days here

**Comment by JPAchilles** [comment]
Mod works good, merged into dev
